//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//   name:
//
//   student number:
//when you finish, please name this file as your student number.c
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "stdio.h"
#include "stdlib.h"
#include "time.h"
#include "math.h"
#define N 15
typedef struct node
{
	int data;
	struct node *next;
}LI;
LI *createlist();//create an ordered list and return the head of list
void insertnode(LI *head,int x);//insert a node to an ordered list
void showlist(LI *head);//show the list
void common(LI *A,LI *B);//find the common node in both A and B, then save the result in list A
void delrepeat(LI *head);//del the repeated node in an ordered list

main()
{
	LI *A,*B;
	A=createlist();//create an ordered list. All number are generated by computer.
	B=createlist();//create an ordered list. All number are generated by computer.
	delrepeat(A);//del the repeated node in the ordered list A
	delrepeat(B);//del the repeated node in the ordered list B
	printf("The original data is:\n");
	showlist(A);//show the list A
	showlist(B);//show the list B
	common(A,B);//find the common data in both A and B, then save the result in list A.This function you should finish by youself.
	printf("The commom number in both A and B is:\n");
	showlist(A);//show the common data, i.e. list A	
}

LI *createlist()
{
	LI *head;
	int i,x;
	head=(LI *)malloc(sizeof(LI));
	head->next=NULL;	
	for(i=0;i<N;i++)
	{
		x=rand()%30;
		insertnode(head,x);		
	}
	return head;
}
void insertnode(LI *head,int x)
{
	LI *p,*p1,*q;
	q=(LI *)malloc(sizeof(LI));
	q->data=x;
	p1=head;p=p1->next;
	while(p)
	{
		if(p->data<x)
		{
			p1=p;
			p=p->next;
		}
		else
			break;
	}
	p1->next=q;
	q->next=p;
}
void showlist(LI *head)
{
	LI *p=head->next;
	if(!p)
	{
		printf("the list is enmpty\n");
		return;
	}
	while(p)
	{
		printf("%4d",p->data);
		p=p->next;
	}
	printf("\n");
}


void delrepeat(LI *head)
{
	LI *p,*p1;
	if(head->next==NULL ||head->next->next==NULL)
		return;
	p1=head->next;
	p=p1->next;
	while(p)
	{
		if(p->data==p1->data)
		{
			p1->next=p->next;
			free(p);
			p=p1->next;
		}
		else
		{
			p1=p;
			p=p->next;
		}
	}	
}

void common(LI *A,LI *B)
 
{
    
     LI *c = (LI*)malloc(sizeof(LI));
     c->data=0;
     LI *tempc =(LI*)malloc(sizeof(LI));
     tempc->data=0;
    tempc->next=NULL;
     c->next=tempc;
     
     
     LI *tempa=A;
     LI *tempb=B;
     A=A->next;
     B=B->next;
    
     LI *t = tempc;
  while(A != NULL){
      while(B!=NULL){
          if(A->data == B->data){
             tempc->next=(LI*)malloc(sizeof(LI));
             tempc =tempc->next;
             tempc->data=A->data;
      
          
          }
          B=B->next;
      }
      B=tempb;
      A=A->next;
  }
  
  A =tempa;
  
   c=c->next;
   *A=*c;
	
}
